### ISSUE TITLE
ExtTransferSwitch not switching

### ISSUE THREAD

**Issue by JohnJayMack** [kwindrem/ExtTransferSwitch#8]
[ExtTranferSwitch.txt](https://github.com/kwindrem/ExtTransferSwitch/files/11985435/ExtTranferSwitch.txt)
Kevin,  

I hope that this is the correct place where you wanted me to post.  

Today has been busy.  After establishing ssh access, I ran the cmd that you sent.  Attached is the output.  I then tried the digital input and could not make the AC Input Pane switch.  

Next, I tried a power down on the Cerbo GX, about 5 minutes, then a power up.  The system still does not change when the Digital 1 signal is applied.  

Is there a way that I can see or verify that the Digital 1 signal is coming in like it should?  

All for now.  Your help is greatly appreciated.

**Comment by kwindrem** [comment]
The service that manages the internal state changes is not detecting the digital input. There should be a message right after the one that reports the input type value that indicates a digital input of that type was detected, but that message is not present.

You should see an entry in the device menu "External AC Input transfer switch, but I suspect you will not see that either.

Navigate to Settings / I/O / Digital inputs and verify the input type shows External transfer switch. If not, select the digital input and reselect the type. Note that when the Venus OS firmware changes, there is a chance the input type will need to be reset. This is due to Victron adding additional input types which I have no control over.

Once you have the digital input type set up properly, the setting shown in the device menu should change from On grid to On generator when you change the input state.

**Comment by JohnJayMack** [comment]
In Device List Menu, I have "External AC Input transfer switch 'on grid'"
Next level down -
State On Grid
Setup  Enable Alarm OFF
            Inverted OFF

under device:
   Connected   Yes
   Connection  /dev/gpio/digital_input_1
   Product   External AC Input transfer switch
   Product ID   0xA166
   Firmware version   --
   VRM Instance 1

Is there a way for me to monitor the Digital Input 1 state from either the monitor or via ssh, or in some other manner?  I have tested my connections with a multimeter, and I have used a hard wire jumper to simulate the input.  What I have not figured out is how to see in software the change of state of the input when the external mechanical input is changed.  

I have seen information that suggests that Modbus-TCP might be configurable to show the status of the Digital inputs, but I have not figured out how, yet.  If you have a suggestion on using the Modbus in this situation, please advise.  

My next thought is to move the input to a different digital input and see if that helps.

Thanks for the help.

Jay

**Comment by kwindrem** [comment]
The entry in the device list for External Ac input transfer switch will change from on grid when the digital input is not active to on generator when it is active. If you are not seeing this, then the digital input is wired wrong.

Make sure you are using digital input 1 or what ever input you are intending to use. If it's not working, try another input to see if the original input is for some reason not working.

**Comment by JohnJayMack** [comment]
The information on the External Ac input is switching between Grid with no input and On Generator when signal is present, but the AC input still shows On Grid.  It is not changing.   I have tried Inputs 1 & 2 with the same result.

**Comment by kwindrem** [comment]
It looks like you may have had a more recent firmware version installed which messed up my logic to determine the digital input type for the transfer switch. I need to rethink this.

For now, if you are willing to upgrade to v3.00 firmware, this should resolve the issue.

**Comment by JohnJayMack** [comment]
I am upgrading now.  Will test tomorrow and report results.

Thanks,

**Comment by JohnJayMack** [comment]
This morning, I put the jumper back on the digital input and found that I had disabled the Touch Screen.  I removed the jumper on the Digital Input 1 but the Touch Screen remained disabled.  I was able to login on the VRM portal and change the Digital Input 1 back to Disable to re-enable the Touch Screen.

Next, for Digital Input 1, I set it to ExtTransferSwitch.  In the Device list, the ExtTransferSwitch reported On Grid.  I installed the jumper and the Ext changed to On Generator. but the AC Input page still shows On Grid.  I pulled the jumper and the Ext switched to On Grid, but the AC Input page stays the same, On Grid.
I have a question.  In the Ext Setup page, there are two settings, Enable Alarm and Inverted.  Both are Off.  Is that the correct position.  Also, in the Device page, the Firmware Version reports as two dashes, '--'.

At some point, by mistake, I shut the entire system down.  I finally got the system back up and NOW the Digital 1 Input causes the AC Input limit to switch.  I am currently running on 50 amp shore power.  I had set the Generator Input to 64 Amps.  The Input limit shows that it changes properly between Grid and Generator, but on Generator, the Grid page is shown although  none of the selections are selected.  In other words, when on Grid, I can change the AC Input limits, but on Generator, I do not see how to change the AC Input limits.

In the Settings/Display & Language/Guimods I see where I can set the presets for AC1 - AC4, but I do not see where to set the Generator AC present.  I tried putting the system back into generator mode, but the AC Input Detail page still shows the Grid settings although none are active/highlighted.

Sorry for the long post.

**Comment by kwindrem** [comment]
You use the same AC input current limit while on generator to set that limit.

**Comment by JohnJayMack** [comment]
I do not understand.  When on Generator, the current limit switches to 65 amps.  No where on the AC Input page is 65 amps showing up.  It was in January when I set the 65 amp limit and I dimly remember a second page showing up with a different Input current limit.  Are you saying that when I go to Generator, I choose one of the presets AC1 - AC4 and boost that input up to the required Generator setting?  Currently when I select Grid, the 48 amp input turns black showing active.  When on generator, all tiles are gray.

**Comment by kwindrem** [comment]
Either use one of the presets or adjust the current with the up/down buttons and accept the new value.

The generator and grid values are stored separately but you can only see (and change) the active one.

There has never been a second page to set generator current limit directly.

**Comment by JohnJayMack** [comment]
Thank you for your help.  The system appears to be working.  I started the Generator and the Input Current Limit changes to the Generator value.   Now I have to troubleshoot something that I have changed that is causing the system to drop all power when I switch AC inputs.  I am sure that it has to do with the accidental shutdown I caused from the Touch 50 screen.  

Thanks again.  I believe that this issue is resolved.

**Comment by kwindrem** [comment]
ExtTransferSwitch changes stop when AC available also. It is turned off when switching to generator, but should be set to on when on grid so the generator doesn't run while the transfer switch is in the grid position. But this needs to be set manually because there may be times it is not desired.

Generator Warm-up and Cool-down periods cause an AC ignore. Also there is a 30 second period when switching from generator that allows the generator to completely shut down before accepting it as the AC source again. However this delay should end when the external transfer switch indicates On Grid.

**Comment by kwindrem** [comment]
I have resolved the issue with grid/generator switching not working older versions of Venus OS. Version v2.18 is now available.

I believe the issue was in the way I was discovering the digital input and the fact that a system at a later version of Venus OS then downgraded to a previous version didn't reset the parameter I was testing.
